config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :barrows do
    resources :bookings, only: [:new, :create]
  end
  devise_for :users
  get 'profile', to: 'barrows#my_barrows', as: :my_barrows
  resources :bookings, only: [:edit, :destroy]
  get 'booking_success/:id', to: 'bookings#success', as: :success
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barrow.rb
class Barrow < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :description, presence: true
  validates :name, presence: true
  validates :category, presence: true, inclusion: { in: ['Thermique', 'Manuel', 'Electrique', 'AssistantIncluded', 'Arc-en-ciel'] }
  validates :price, presence: true, numericality: { only_integer: true }

  has_one_attached :photo

  geocoded_by :town
  after_validation :geocode, if: :will_save_change_to_town?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :barrow
  validates :booking_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :barrows, dependent: :destroy
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # include Pundit

  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end

private

  # def skip_pundit?
  #   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  # end

end

app/controllers/barrows_controller.rb
class BarrowsController < ApplicationController
  before_action :set_barrow, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def town
  [town, city, state, country].compact.join(', ')
  end

  # GET /barrows
  # GET /barrows.json
  def index
    cookies[:booking_date] = params[:search][:booking_date]
    if params[:search].present?
      if params[:search][:category].present?
      @barrows = Barrow.where("town ILIKE ?", "%#{params[:search][:town]}%").where("category ILIKE ?", "%#{params[:search][:category]}%")
      else
      @barrows = Barrow.where("town ILIKE ?", "%#{params[:search][:town]}%")
      end
    else
      @barrows = Barrow.all
    end


    # authorize @barrows
    # @barrows = Barrow.where(town: param[:town] AND category: params[:category])
    # @barrows = policy_scope(Barrow).order(created_at: :desc)
  end

  # GET /my_barrows
  def my_barrows
    @barrows = Barrow.where(user_id: current_user.id)
    @bookings = Booking.where(user_id: current_user.id)
    # authorize @barrows
    # authorize @bookings
  end
  # GET /barrows/1
  # GET /barrows/1.json
  def show
    @booking = Booking.new
    @barrows_coordinates = Barrow.geocoded
    a = @barrows_coordinates.find(params[:id])
        @markers =
            {
              lat: a.latitude,
              lng: a.longitude
            }
  end

  # GET /barrows/new
  def new
    @barrow = Barrow.new
    # authorize @barrow
  end

  # GET /barrows/1/edit
  def edit
  end

  # POST /barrows
  # POST /barrows.json
  def create
    @barrow = Barrow.new(barrow_params)
    @barrow.user = current_user
    # authorize @barrow

    respond_to do |format|
      if @barrow.save
        format.html { redirect_to barrow_path(@barrow), notice: 'Vous avez bien posté une nouvelle brouette.' }
        format.json { render :show, status: :created, location: @barrow }
      else
        format.html { render :new }
        format.json { render json: @barrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barrows/1
  # PATCH/PUT /barrows/1.json
  def update
    respond_to do |format|
      if @barrow.update(barrow_params)
        format.html { redirect_to my_barrows_path, notice: 'La brouette a bien été modifiée.' }
        format.json { render :show, status: :ok, location: @barrow }
      else
        format.html { render :edit }
        format.json { render json: @barrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barrows/1
  # DELETE /barrows/1.json
  def destroy
    @barrow.destroy
    respond_to do |format|
      format.html { redirect_to my_barrows_path, notice: 'Annonce de brouette suuprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barrow
      @barrow = Barrow.find(params[:id])
      # authorize @barrow
    end

    # Only allow a list of trusted parameters through.
    def barrow_params
      params.require(:barrow).permit(:name, :description, :town, :category, :price, :user_id, :photo)
    end

    def booking_params
      params.require(:booking).permit(:booking_date, :user_id, :barrow_id)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def success
    @booking = Booking.find(params[:id])
    @booking.barrow = Barrow.find(@booking.barrow_id)
  end
  # GET /my_bookings
  def my_bookings
    @bookings = Barrow.where(user_id: current_user.id)
    @bookings = Booking.where(user_id: current_user.id)
    # authorize @bookings
  end
  # GET /bookings/1
  # GET /bookings/1.json

  # GET /bookings/new
  def new
    @booking = Booking.new
    # authorize @booking
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_date: cookies[:booking_date])
    @booking.user = current_user
    @booking.barrow = Barrow.find(params[:barrow_id])
    # authorize @booking

    respond_to do |format|
      if @booking.save!
        format.html { redirect_to success_path(@booking), notice: 'booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to my_barrows_path, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to my_barrows_path, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
      # authorize @barrow
    end

    # Only allow a list of trusted parameters through.

    def booking_params
      params.require(:booking).permit(:booking_date, :user_id, :barrow_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
    true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/barrows/_form.html.erb
<%= simple_form_for(@barrow) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<h1 class="newbarrowtitre">Add a barrow</h1>
  <div class="form-inputs">
    <div class="bordure-jaune jordure-baune"><%= f.input :name, label: false, placeholder: "Nom", input_html: { id: "inputdebarrow" } %></div>
    <div class="bordure-jaune jordure-baune"><%= f.input :description, label: false, placeholder: "Description", input_html: { id: "inputdebarrow" } %></div>
    <div class="bordure-jaune jordure-baune"><%= f.input :town, label: false, placeholder: "Ville", input_html: { id: "inputdebarrow" } %></div>
    <div class="bordure-jaune jordure-baune"><%= f.input :category, include_blank: false, collection: ['Thermique', 'Manuelle', 'Electrique', 'AssistantIncluded', 'Arc-en-ciel'].map {|d| [d, d]}.unshift(['Choisir catégorie', '']), label: false, placeholder: "Catégorie", input_html: { id: "inputdebarrow" } %></div>
    <div class="bordure-jaune jordure-baune"><%= f.input :price, label: false, placeholder: "Prix", input_html: { id: "inputdebarrow" } %></div>
    <div class="laphoto"> <%= f.input :photo, as: :file, label: false, input_html: { id: "iddephoto"} %></div>
  </div>

  <div class="form-actions" id="uhohpoopy">
    <div id="boutonsubmit"> <%= f.button :submit %></div>
    <div id="boutonback"><%= link_to 'Back', barrows_path, id: "buttonback" %></div>
  </div>
<% end %>

app/views/barrows/edit.html.erb
<h1>Editing Barrow</h1>

<%= render 'form', barrow: @barrow %>

<%= link_to 'Show', @barrow %> |
<%= link_to 'Back', barrows_path %>

app/views/barrows/my_barrows.html.erb
<body>


<div class="container">
<br>

<h1 class="my-barrows">Mes brouettes à moi rien qu'à moi</h1>

<br>

<div class="cards">
<% if @barrows.empty?  %>
<p>
Vous n'avez posté aucune annonce de brouette.
Cliquez <%= link_to "ici", new_barrow_path %> pour poster une annonce de brouette.
</p>
<% else %>
  <% @barrows.each do |barrow| %>
    <div class="card-trip">
      <%= cl_image_tag barrow.photo.key, height: 500, width: 730, crop: :fill if barrow.photo.attached? %>
      <p><%= link_to '+', barrow, method: :delete, data: { confirm: 'Voulez-vous supprimer cette brouette?' }, class: "link-destroy" %></p>
      <div class="card-trip-infos">
        <div>
          <h2><%=barrow.name%></h2>
          <h6><%= barrow.town %></h6>
          <p><%=barrow.category%></p>
          <p><%= link_to 'Edit', edit_barrow_path(barrow), class: "btn btn-ghost" %></p>


        </div>
        <h2 class="card-trip-pricing"><%= barrow.price %> €</h2>
      </div>
    </div>
  <% end %>
<% end %>
</div>
<br>
<br>

<h1 class="my-barrows">Les brouettes que j'ai loué</h1>

<br>



<div class="cards">
<% if @bookings.empty?  %>
<p>
  Pas encore de locations. <br>
  Cliquez <%= link_to "ici", root_path %> pour louer une brouette.
</p>
<% else %>
<% @bookings.each do |booking| %>
    <div class="card-trip">
      <%= cl_image_tag booking.barrow.photo.key, height: 500, width: 730, crop: :fill if booking.barrow.photo.attached? %>
      <p><%= link_to '+', booking, method: :delete, data: { confirm: 'Voulez-vous supprimer cette réservation?' }, class: "link-destroy" %></p>
      <div class="card-trip-infos">
        <div>
          <h2><%=booking.booking_date%></h2>
          <h6><%= booking.barrow.name %></h6>
          <br>
        </div>
        <h2 class="card-trip-pricing"><%= booking.barrow.price %> €</h2>
        <div class= "card-trip-user avatar-bordered" >
          <% if booking.barrow.user.photo.attached? %>
            <%= cl_image_tag booking.barrow.user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "anna.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</div>
<br>
<br>

</body>
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Le père brouette vous remercie chaleureusement de votre viste <i class="fas fa-heart"></i>
  </div>
</div>

app/views/barrows/new.html.erb
  <div class="container-lebarrow">
    <div class=newbarrow>
      <%= render 'form', barrow: @barrow %>
    </div>
  </div>
<!-- jambon cuit pestina pesto basilique -->

app/views/barrows/show.html.erb
  <body>

  <p id="notice"><%= notice %></p>


  <div class="container">
  <div class="container-car-desc">
    <div>
    <%= cl_image_tag @barrow.photo.key, height: 500, width: 730, crop: :fill if @barrow.photo.attached? %>
    </div>

    <div class="card-trip-desc">
      <div class="card-body">
        <div class="avatar-username">
          <% if @barrow.user.photo.attached? %>
            <%= cl_image_tag @barrow.user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "avatar_default.png",crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
          <% end %>
          <h5 class="card-text"> <%= @barrow.user.username %> </h5>
        </div>
        <p class="card-text"><%= @barrow.town %></p>
        <p class="card-text"><%= @barrow.user.email %></p>
        <h4 class="card-text price"><%= @barrow.price %> €</h4>
      <div class="card-body">

        <%= link_to 'Louer', barrow_bookings_path(@barrow), method: :post, class: "btn btn-flat"  %>

     </div>

      </div>
    </div>
  </div>


  <br>

  <div class="card-desc">
    <h4 class="title"><%= @barrow.name %></h4>
    <p class="desc"> <%= @barrow.description %></p>
  </div>



  <br>

  <div
    id="map" style="width: 100%; height: 400px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

  <br>



  <%= link_to 'Précédent', my_barrows_path %>

  </div>




  </body>
    <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Le père brouette vous remercie chaleureusement de votre viste <i class="fas fa-heart"></i>
    </div>
  </div>

app/views/bookings/success.html.erb
<body>

<div class="container">
  <div class="success">
    <h1 class="congrats">Félicitati<span>o</span>ns, tu as b<span>oo</span>ké <%= "#{@booking.barrow.name} le #{@booking.booking_date}" %></h1>
  <br>
    <div class="container-car-desc">
      <img id="gif-barrow" src="https://media.giphy.com/media/1avrDdGYCH2a4/source.gif" alt="">
    </div>
    <br>
    <br>
    <br>
    <h2 class="congrats"> Clique <%= link_to "ici", my_barrows_path %> pour aller sur ton profil </h2>
  </div>
</div>

</body>
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Le père brouette vous remercie chaleureusement de votre viste <i class="fas fa-heart"></i>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Le Père Brouette</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<!--     <link rel="stylesheet/scss" type="text/css" href="card.scss"> -->

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC&display=swap" rel="stylesheet">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>

</html>

app/views/pages/home.html.erb
<body class="background-image">
  <div class="container">

      <div class="pomehage">
        <div class="form-homepage">
          <h2 class="texts">Louez une brouette</h2>
          <%= simple_form_for :search, url: barrows_path, method: :get, class: "action" do |f| %>
          <div class="bordure-jaune"><%= f.input :town, input_html: {class: "form-control", id: "exampleInputPassword1"}, label: false, placeholder: "Ville" %></div>
          <div class="bordure-jaune"><%= f.input :category, include_blank: false, collection: ['Thermique', 'Manuelle', 'Electrique', 'Avec Assistant'].map {|d| [d, d]}.unshift(['Toutes', '']), input_html: {class: "form-control", id: "exampleInputEmail1"}, label: false %></div>
          <div class="bordure-jaune"><%= f.input :booking_date, input_html: {class: "form-control", id: "exampleInputEmail1"}, label: false, placeholder: "Date" %></div>
          <%= f.submit "Rechercher", class: "kak", id: "lebouton" %>
        <% end %>
      </div>
        <h1 class="title-pere">Le Père Brouette since 1972</h1>
    </div>
  </div>
</body>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path,  class: "navbar-brand" do  %>
  <%= image_tag "logo_default.png" %>
    <% end %>

   <p class="title">Le Père Br<span>o</span>uette</p>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Profil", my_barrows_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Poster une brouette", new_barrow_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "avatar_default.png", class: "avatar dropdown-toggle image", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profil", my_barrows_path, class: "dropdown-item" %>
            <%= link_to "Mes réservations", my_barrows_path, class: "dropdown-item" %>
            <%= link_to "Mes brouettes", my_barrows_path, class: "dropdown-item" %>
            <%= link_to "Paramètres", my_barrows_path, class: "dropdown-item" %>
            <%= link_to "Sécurité du compte", my_barrows_path, class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>